# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ipedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ipedit.setGeometry(QtCore.QRect(0, 130, 801, 31))
        self.ipedit.setObjectName("ipedit")
        self.hostedit = QtWidgets.QLineEdit(self.centralwidget)
        self.hostedit.setGeometry(QtCore.QRect(0, 170, 801, 31))
        self.hostedit.setObjectName("hostedit")
        self.netedit = QtWidgets.QLineEdit(self.centralwidget)
        self.netedit.setGeometry(QtCore.QRect(0, 210, 801, 31))
        self.netedit.setObjectName("netedit")
        self.sendBttn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBttn.setGeometry(QtCore.QRect(330, 250, 131, 41))
        self.sendBttn.setCheckable(False)
        self.sendBttn.setChecked(False)
        self.sendBttn.setAutoDefault(False)
        self.sendBttn.setDefault(False)
        self.sendBttn.setFlat(False)
        self.sendBttn.setObjectName("sendBttn")
        self.browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(0, 290, 801, 271))
        self.browser.setObjectName("browser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 181, 71))
        self.label.setStyleSheet("font: 16pt \"Modern No. 20\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client Side Window"))
        self.ipedit.setPlaceholderText(_translate("MainWindow", "IP Address with Prefix eg 192.168.0.0/24"))
        self.hostedit.setPlaceholderText(_translate("MainWindow", "Host Number eg 8"))
        self.netedit.setPlaceholderText(_translate("MainWindow", "Number of Networks eg 16"))
        self.sendBttn.setText(_translate("MainWindow", "Send To Server"))
        self.label.setText(_translate("MainWindow", "SUBNETTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
